### ISSUE TITLE
An error/mistake in Easom function

### ISSUE THREAD

**Issue by l-szymanski** [nathanrooy/landscapes#6]
https://github.com/nathanrooy/landscapes/blob/25f1f5d5f73b3b56d181dbd9fa5700086201d8f4/landscapes/single_objective.py#L749

should be

`
return -cos(x)*cos(y)*exp(-((x-pi)**2 - (y-pi)**2))
`

Correct this before another person lose weeks of computation.

**Comment by nathanrooy** [comment]
Thanks for the correction! The library has been updated.
